// data.js
const coursesData = [
    // Semestre 1 - Área Formación Básica
    { id: 1, name: "Introducción a las Ciencias Veterinarias", semester: 1, prerequisites: [], area: "Básica", approved: false, grade: null, description: "Este curso introduce a los estudiantes a los principios fundamentales de las ciencias veterinarias, explorando la historia, ética y el impacto de la profesión." },
    { id: 2, name: "Fundamentos de la Química", semester: 1, prerequisites: [], area: "Básica", approved: false, grade: null, description: "Estudio de los principios básicos de la química, incluyendo estructura atómica, enlaces químicos, reacciones y estequiometría." },
    { id: 3, name: "Biología Celular y Molecular", semester: 1, prerequisites: [], area: "Básica", approved: false, grade: null, description: "Exploración de la estructura y función de las células, así como los procesos moleculares que sustentan la vida." },
    { id: 4, name: "Matemática", semester: 1, prerequisites: [], area: "Básica", approved: false, grade: null, description: "Desarrollo de habilidades matemáticas esenciales para la resolución de problemas en ciencias biológicas y veterinarias." },
    { id: 5, name: "Zoología", semester: 1, prerequisites: [], area: "Básica", approved: false, grade: null, description: "Estudio de la diversidad del reino animal, su clasificación, evolución y características biológicas." },
    { id: 6, name: "Fundamentos de la Física", semester: 1, prerequisites: [], area: "Básica", approved: false, grade: null, description: "Introducción a los conceptos fundamentales de la física y su aplicación en sistemas biológicos." },

    // Semestre 2 - Área Formación Básica / Disciplinar
    { id: 7, name: "Anatomía Animal I", semester: 2, prerequisites: [5], area: "Disciplinar", approved: false, grade: null, description: "Estudio detallado de la anatomía macroscópica de los principales sistemas en animales domésticos." }, // Prereq: Zoología (5)
    { id: 8, name: "Praderas y Especies Forrajeras", semester: 2, prerequisites: [3], area: "Disciplinar", approved: false, grade: null, description: "Análisis de la composición, manejo y valor nutricional de praderas y especies forrajeras para la alimentación animal." }, // Prereq: Biología Celular y Molecular (3)
    { id: 9, name: "Fundamentos de Bioquímica", semester: 2, prerequisites: [2, 3], area: "Básica", approved: false, grade: null, description: "Estudio de las bases químicas de los procesos biológicos en organismos vivos." }, // Prereq: Fundamentos de la Química (2), Biología Celular y Molecular (3)
    { id: 10, name: "Histoembriología Veterinaria", semester: 2, prerequisites: [3], area: "Básica", approved: false, grade: null, description: "Estudio microscópico de tejidos y órganos, y el desarrollo embrionario en animales." }, // Prereq: Biología Celular y Molecular (3)
    { id: 11, name: "Ecología", semester: 2, prerequisites: [4, 5], area: "Básica", approved: false, grade: null, description: "Exploración de las interacciones entre los organismos y su ambiente, y los principios de la conservación." }, // Prereq: Matemática (4), Zoología (5)
    { id: 12, name: "Electivo 1", semester: 2, prerequisites: [], area: "Electiva", approved: false, grade: null, description: "Curso a elección del estudiante para profundizar en un área de interés." }, // Electivo

    // Semestre 3 - Área Formación Disciplinar
    { id: 13, name: "Anatomía Animal II", semester: 3, prerequisites: [7], area: "Disciplinar", approved: false, grade: null, description: "Continuación del estudio de la anatomía animal, profundizando en sistemas específicos y comparativos." }, // Prereq: Anatomía Animal I (7)
    { id: 14, name: "Nutrición y Alimentación Animal", semester: 3, prerequisites: [8, 9], area: "Disciplinar", approved: false, grade: null, description: "Principios de la nutrición animal, formulación de dietas y manejo alimentario en diferentes especies." }, // Prereq: Praderas y Especies Forrajeras (8), Fundamentos de Bioquímica (9)
    { id: 15, name: "Fisiología Veterinaria", semester: 3, prerequisites: [9, 10], area: "Disciplinar", approved: false, grade: null, description: "Estudio de las funciones y mecanismos de los sistemas orgánicos en animales." }, // Prereq: Fundamentos de Bioquímica (9), Histoembriología Veterinaria (10)
    { id: 16, name: "Práctica Inicial", semester: 3, prerequisites: [7, 11], area: "Disciplinar", approved: false, grade: null, description: "Primera experiencia práctica en entornos relacionados con la medicina veterinaria." }, // Prereq: Anatomía Animal I (7), Ecología (11)
    { id: 17, name: "Inmunología General", semester: 3, prerequisites: [3, 9], area: "Básica", approved: false, grade: null, description: "Conceptos fundamentales del sistema inmune y su respuesta a patógenos." }, // Prereq: Biología Celular y Molecular (3), Fundamentos de Bioquímica (9)
    { id: 18, name: "Bioestadística", semester: 3, prerequisites: [4], area: "Básica", approved: false, grade: null, description: "Aplicación de métodos estadísticos para el análisis de datos en ciencias biológicas y veterinarias." }, // Prereq: Matemática (4)
    { id: 19, name: "Electivo 2", semester: 3, prerequisites: [], area: "Electiva", approved: false, grade: null, description: "Curso a elección del estudiante para profundizar en un área de interés." }, // Electivo

    // Semestre 4 - Área Formación Disciplinar
    { id: 20, name: "Etología y Bienestar Animal", semester: 4, prerequisites: [15], area: "Disciplinar", approved: false, grade: null, description: "Estudio del comportamiento animal y los principios que rigen su bienestar." }, // Prereq: Fisiología Veterinaria (15)
    { id: 21, name: "Histopatología", semester: 4, prerequisites: [15], area: "Disciplinar", approved: false, grade: null, description: "Estudio de las alteraciones microscópicas de los tejidos causadas por enfermedades." }, // Prereq: Fisiología Veterinaria (15)
    { id: 22, name: "Microbiología Veterinaria", semester: 4, prerequisites: [17], area: "Disciplinar", approved: false, grade: null, description: "Identificación y caracterización de microorganismos patógenos en animales y sus implicaciones." }, // Prereq: Inmunología General (17)
    { id: 23, name: "Conservación de Fauna Silvestre", semester: 4, prerequisites: [11], area: "Disciplinar", approved: false, grade: null, description: "Principios y estrategias para la conservación de especies y ecosistemas silvestres." }, // Prereq: Ecología (11)
    { id: 24, name: "Métodos de Investigación en Salud", semester: 4, prerequisites: [18], area: "Básica", approved: false, grade: null, description: "Diseño y ejecución de estudios de investigación en el ámbito de la salud animal." }, // Prereq: Bioestadística (18)
    { id: 25, name: "Electivo 3", semester: 4, prerequisites: [], area: "Electiva", approved: false, grade: null, description: "Curso a elección del estudiante para profundizar en un área de interés." }, // Electivo

    // Semestre 5 - Área Formación Disciplinar
    { id: 26, name: "Genética en Ciencias Veterinarias", semester: 5, prerequisites: [18], area: "Disciplinar", approved: false, grade: null, description: "Aplicación de los principios genéticos en la mejora animal y el control de enfermedades hereditarias." }, // Prereq: Bioestadística (18)
    { id: 27, name: "Epidemiología Veterinaria", semester: 5, prerequisites: [24], area: "Disciplinar", approved: false, grade: null, description: "Estudio de la distribución y determinantes de enfermedades en poblaciones animales." }, // Prereq: Métodos de Investigación en Salud (24)
    { id: 28, name: "Fisiopatología Veterinaria", semester: 5, prerequisites: [13, 21], area: "Disciplinar", approved: false, grade: null, description: "Estudio de los mecanismos de las enfermedades y sus efectos en la función orgánica." }, // Prereq: Anatomía Animal II (13), Histopatología (21)
    { id: 29, name: "Gestión Ambiental y Desarrollo Sustentable", semester: 5, prerequisites: [23], area: "Disciplinar", approved: false, grade: null, description: "Análisis de la interacción entre la actividad humana y el medio ambiente, con foco en la sostenibilidad." }, // Prereq: Conservación de Fauna Silvestre (23)
    { id: 30, name: "Gestión Contable y Financiera", semester: 5, prerequisites: [18], area: "Básica", approved: false, grade: null, description: "Principios de contabilidad y finanzas aplicados a la gestión de clínicas o empresas veterinarias." }, // Prereq: Bioestadística (18)
    { id: 31, name: "Electivo 4", semester: 5, prerequisites: [], area: "Electiva", approved: false, grade: null, description: "Curso a elección del estudiante para profundizar en un área de interés." }, // Electivo

    // Semestre 6 - Área Formación Disciplinar
    { id: 32, name: "Semiología Veterinaria", semester: 6, prerequisites: [20, 28], area: "Disciplinar", approved: false, grade: null, description: "Adquisición de habilidades para la anamnesis, exploración física y el diagnóstico clínico en animales." }, // Prereq: Etología y Bienestar Animal (20), Fisiopatología Veterinaria (28)
    { id: 33, name: "Reproducción Animal", semester: 6, prerequisites: [28], area: "Disciplinar", approved: false, grade: null, description: "Fisiología y patología de la reproducción en diferentes especies animales." }, // Prereq: Fisiopatología Veterinaria (28)
    { id: 34, name: "Anatomía Patológica", semester: 6, prerequisites: [28], area: "Disciplinar", approved: false, grade: null, description: "Diagnóstico de enfermedades mediante el estudio macroscópico y microscópico de lesiones." }, // Prereq: Fisiopatología Veterinaria (28)
    { id: 35, name: "Microbiología de los Alimentos", semester: 6, prerequisites: [22, 24], area: "Disciplinar", approved: false, grade: null, description: "Estudio de los microorganismos asociados a los alimentos y su impacto en la salud pública." }, // Prereq: Microbiología Veterinaria (22), Métodos de Investigación en Salud (24)
    { id: 36, name: "Práctica Intermedia", semester: 6, prerequisites: [16, 20], area: "Disciplinar", approved: false, grade: null, description: "Consolidación de habilidades clínicas y de manejo animal en un entorno real." }, // Prereq: Práctica Inicial (16), Etología y Bienestar Animal (20)
    { id: 37, name: "Electivo 5", semester: 6, prerequisites: [], area: "Electiva", approved: false, grade: null, description: "Curso a elección del estudiante para profundizar en un área de interés." }, // Electivo

    // Semestre 7 - Área Formación Disciplinar
    { id: 38, name: "Sistemas de Producción Animal", semester: 7, prerequisites: [14, 26], area: "Disciplinar", approved: false, grade: null, description: "Análisis de los sistemas de producción animal, su eficiencia y sostenibilidad." }, // Prereq: Nutrición y Alimentación Animal (14), Genética en Ciencias Veterinarias (26)
    { id: 39, name: "Farmacología Veterinaria", semester: 7, prerequisites: [28], area: "Disciplinar", approved: false, grade: null, description: "Estudio de los fármacos utilizados en medicina veterinaria, sus mecanismos de acción y uso terapéutico." }, // Prereq: Fisiopatología Veterinaria (28)
    { id: 40, name: "Enfermedades Producidas por Agentes Biológicos I", semester: 7, prerequisites: [27, 35], area: "Disciplinar", approved: false, grade: null, description: "Diagnóstico, prevención y control de enfermedades infecciosas y parasitarias en animales." }, // Prereq: Epidemiología Veterinaria (27), Microbiología de los Alimentos (35)
    { id: 41, name: "Procedimientos Clínicos", semester: 7, prerequisites: [32], area: "Disciplinar", approved: false, grade: null, description: "Desarrollo de habilidades prácticas en técnicas y procedimientos clínicos veterinarios." }, // Prereq: Semiología Veterinaria (32)
    { id: 42, name: "Imagenología", semester: 7, prerequisites: [34], area: "Disciplinar", approved: false, grade: null, description: "Aplicación de técnicas de diagnóstico por imagen (radiografía, ecografía, etc.) en veterinaria." }, // Prereq: Anatomía Patológica (34)
    { id: 43, name: "Inteligencia Artificial Aplicada a la Salud", semester: 7, prerequisites: [18], area: "Disciplinar", approved: false, grade: null, description: "Exploración de cómo la IA puede mejorar el diagnóstico, tratamiento y gestión en medicina veterinaria." }, // Prereq: Bioestadística (18)

    // Semestre 8 - Área Formación Disciplinar
    { id: 44, name: "Laboratorio Clínico y Biotecnología", semester: 8, prerequisites: [34, 40], area: "Disciplinar", approved: false, grade: null, description: "Análisis e interpretación de pruebas de laboratorio y aplicaciones biotecnológicas en veterinaria." }, // Prereq: Anatomía Patológica (34), Enfermedades producidas por agentes biológicos I (40)
    { id: 45, name: "Investigación en Ciencias Veterinarias", semester: 8, prerequisites: [24], area: "Disciplinar", approved: false, grade: null, description: "Desarrollo de proyectos de investigación científica en el campo de las ciencias veterinarias." }, // Prereq: Métodos de Investigación en Salud (24)
    { id: 46, name: "Enfermedades Producidas por Agentes Biológicos II", semester: 8, prerequisites: [40, 39], area: "Disciplinar", approved: false, grade: null, description: "Continuación del estudio de enfermedades infecciosas y parasitarias, con énfasis en el control y la prevención." }, // Prereq: Enfermedades producidas por agentes biológicos I (40), Farmacología Veterinaria (39)
    { id: 47, name: "Principios de Cirugía y Anestesiología", semester: 8, prerequisites: [39, 41], area: "Disciplinar", approved: false, grade: null, description: "Fundamentos de las técnicas quirúrgicas y el manejo anestésico en animales." }, // Prereq: Farmacología Veterinaria (39), Procedimientos Clínicos (41)
    { id: 48, name: "Medicina Interna", semester: 8, prerequisites: [32, 42], area: "Disciplinar", approved: false, grade: null, description: "Diagnóstico y tratamiento de enfermedades no quirúrgicas en animales de compañía y producción." }, // Prereq: Semiología Veterinaria (32), Imagenología (42)
    { id: 49, name: "Bioética", semester: 8, prerequisites: [], area: "Básica", approved: false, grade: null, description: "Análisis de los dilemas éticos en la práctica veterinaria y la investigación animal." }, // Sin prerrequisitos explícitos

    // Semestre 9 - Área Formación Disciplinar
    { id: 50, name: "Salud Pública Veterinaria", semester: 9, prerequisites: [46], area: "Disciplinar", approved: false, grade: null, description: "El rol del veterinario en la salud pública, seguridad alimentaria y control de zoonosis." }, // Prereq: Enfermedades producidas por agentes biológicos II (46)
    { id: 51, name: "Unidad de Investigación I", semester: 9, prerequisites: [45, 49], area: "Disciplinar", approved: false, grade: null, description: "Primera etapa de un proyecto de investigación tutelado en ciencias veterinarias." }, // Prereq: Investigación en Ciencias Veterinarias (45), Bioética (49)
    { id: 52, name: "Internado de Pequeños Animales I", semester: 9, prerequisites: [44, 47, 48], area: "Disciplinar", approved: false, grade: null, description: "Experiencia clínica intensiva en el diagnóstico y tratamiento de enfermedades en pequeños animales." }, // Prereq: Laboratorio Clínico y Biotecnología (44), Principios de Cirugía y Anestesiología (47), Medicina Interna (48)
    { id: 53, name: "Internado de Animales Mayores I", semester: 9, prerequisites: [44, 47, 48], area: "Disciplinar", approved: false, grade: null, description: "Experiencia clínica intensiva en el diagnóstico y tratamiento de enfermedades en animales de producción." }, // Prereq: Laboratorio Clínico y Biotecnología (44), Principios de Cirugía y Anestesiología (47), Medicina Interna (48)
    { id: 54, name: "Formulación y Evaluación de Proyectos Veterinarios", semester: 9, prerequisites: [30, 38], area: "Disciplinar", approved: false, grade: null, description: "Desarrollo de habilidades para diseñar, planificar y evaluar proyectos en el ámbito veterinario." }, // Prereq: Gestión Contable y Financiera (30), Sistemas de Producción Animal (38)
    { id: 55, name: "Gestión Veterinaria", semester: 9, prerequisites: [30, 38], area: "Disciplinar", approved: false, grade: null, description: "Principios de gestión y administración aplicados a la práctica y negocios veterinarios." }, // Prereq: Gestión Contable y Financiera (30), Sistemas de Producción Animal (38)
    { id: 56, name: "Práctica Profesional", semester: 9, prerequisites: [], area: "Disciplinar", approved: false, grade: null, description: "Práctica supervisada para aplicar los conocimientos y habilidades adquiridos en un entorno profesional real." }, // Prereq: Obtención de licenciatura (asumiendo que se debe haber completado un % significativo)

    // Semestre 10 - Área Formación Disciplinar
    { id: 57, name: "Una Salud", semester: 10, prerequisites: [50, 54], area: "Disciplinar", approved: false, grade: null, description: "Enfoque holístico de la salud que integra la salud humana, animal y ambiental." }, // Prereq: Salud Pública Veterinaria (50), Formulación y Evaluación de Proyectos Veterinarios (54)
    { id: 58, name: "Unidad de Investigación II", semester: 10, prerequisites: [51], area: "Disciplinar", approved: false, grade: null, description: "Segunda etapa del proyecto de investigación, culminando con la presentación de resultados." }, // Prereq: Unidad de Investigación I (51)
    { id: 59, name: "Internado Electivo: Pequeños Animales II", semester: 10, prerequisites: [], area: "Disciplinar", approved: false, grade: null, description: "Internado avanzado en clínica de pequeños animales, con mayor autonomía y casos complejos." }, // Internado Electivo
    { id: 60, name: "Internado Electivo: Animales Mayores", semester: 10, prerequisites: [], area: "Disciplinar", approved: false, grade: null, description: "Internado avanzado en clínica de animales de producción, con énfasis en manejo de rebaños y patologías específicas." }, // Internado Electivo
    { id: 61, name: "Internado Electivo: Conservación, Biodiversidad y Medio Ambiente", semester: 10, prerequisites: [], area: "Disciplinar", approved: false, grade: null, description: "Internado enfocado en la medicina de la conservación, manejo de fauna silvestre y ecosistemas." }, // Internado Electivo
    { id: 62, name: "Internado Electivo: Producción y Sistemas de Aseguramiento de la Calidad", semester: 10, prerequisites: [], area: "Disciplinar", approved: false, grade: null, description: "Internado especializado en la producción animal, seguridad alimentaria y sistemas de calidad en la industria." }, // Internado Electivo
    { id: 63, name: "Orientación Laboral y Responsabilidad Ética en Medicina Veterinaria", semester: 10, prerequisites: [36], area: "Disciplinar", approved: false, grade: null, description: "Preparación para la inserción laboral y profundización en las responsabilidades éticas y legales de la profesión." }, // Prereq: Práctica Intermedia (36)
];
